defaults:
  - process: process1
  - model: model1
  - _self_

raw: 
  path: data/raw/raw_ufo_data.csv

locations:
  dir: data/processed
  name: locations.csv
  path: ${locations.dir}/${locations.name}

durations:
  dir: data/processed
  name: durations.json
  path: ${durations.dir}/${durations.name}

processed:
  dir: data/processed
  name: us_ufo_data.csv
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}